### ISSUE TITLE
request.auth is null in security rules so Firebase API calls fail due to permissions.

### ISSUE THREAD

**Issue by braincomb** [robingenz/capacitor-firebase-authentication#103]
**Plugin version:**

0.3.11

**Platform(s):**

Android

**Current behavior:**

On a physical Android device, any calls made to the Firebase Firestore or Storage API would fail if the Security Rules are set to only accept authenticated users. 
Example of Security Rules below where write calls would only be accepted for authenticated users:

```javascript
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
  }
}
```

The error returned:

```
2021-11-17 12:01:55.373 9229-9229/myapp E/Capacitor/Console: File: http://localhost/tabs/add - Line 0 - Msg: Uncaught (in promise) FirebaseError: Firebase Storage: User does not have permission to access 'ugc_images/1637179300409.jpeg'. (storage/unauthorized)
    {
      "error": {
        "code": 403,
        "message": "Permission denied."
      }
    }
```

If we remove the `if request.auth != null;` bit from the rules, then everything would work correctly as expected.

So for some reason the authentication payload is not being sent to Firebase. Even though I'm pretty sure that the user has signed in successfully, and `getCurrentUser()` returns the user object.

I was only able to make this work on the web layer (PC browser) when we use JavaScript JS SDK with `"skipNativeAuth": true`, but that defeats the purpose because we want the app to function on the physical device.

**Expected behavior:**

Authentication payload to be sent to respect Security Rules with `request.auth` conditions.

**Steps to reproduce:**

**Related code:**

```javascript
// capacitor.config.json
{
  "appId": "myapp",
  "appName": "myapp",
  "webDir": "dist",
  "bundledWebRuntime": false,
  "plugins": {
    "FirebaseAuthentication": {
      "skipNativeAuth": false,
      "providers": [
        "twitter.com",
        "google.com",
        "facebook.com"
      ]
    }
  }
}
```

```javascript
// Login.vue
const signInWithGoogle = async () => {
  const result = await FirebaseAuthentication.signInWithGoogle();
  console.log(result.user); // successfully get result
};
```

**Other information:**

**Capacitor doctor:**

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5

[success] Android looking great! 👌
[error] Xcode is not installed

I'm currently baffled and not sure how to proceed  or if I'm missing something. Any help would be appreciated!  

Thanks!

**Comment by robingenz** [comment]
Hi @braincomb,
thank you for this detailed message.
This plugin offers you the possibility to authenticate your users either on native layer or on web layer.
If you authenticate your users on native layer, then the Firebase JS SDK will not know about it.
You would have to use native SDKs only in this case. I'm aware that the options here are not that great yet at the moment. I'm currently working on a solution and will release more Firebase plugins in the coming weeks and months.
If you want to use the Firebase JS SDK, then you need to authenticate the user on the web layer.
For this, please check out [this guide](https://github.com/robingenz/capacitor-firebase-authentication/blob/main/docs/firebase-js-sdk.md).

Could I help you with this?

**Comment by braincomb** [comment]
Hi @robingenz,

Using the Firebase JS SDK was exactly what I was looking for, I was able to make it work with no issues so far.

Thanks again!
