### ISSUE TITLE
Error "FirebaseAuthentication" plugin is not implemented on android

### ISSUE THREAD

**Issue by jofftiquez** [robingenz/capacitor-firebase-authentication#106]
I already added all the necessary libraries in my project gradle, and module gradle in android. But I am still getting this error. Is there something I missed?

------------------------------------------------------

**Plugin version:**
> ^0.3.12

**Platform(s):**
> Android

**Current behavior:**
Everything is setup properly and there are no console error, no build errors either. But when I clicked the button that invokes the main signing method:

```js
const result = await FirebaseAuthentication.signInWithGoogle();
```

I am getting the toast message that says: `"FirebaseAuthentication" plugin is not implemented on android`

**Expected behavior:**
When I click the signin button, a prompt will appear or something? 

**Steps to reproduce:**

**Related code:**

Vue component: 

```js
import { FirebaseAuthentication } from '@robingenz/capacitor-firebase-authentication';
...
const result = await FirebaseAuthentication.signInWithGoogle();
```

capacitor.config.json

```json
{
  "appId": "org.my.app",
  "appName": "My App",
  "bundledWebRuntime": false,
  "npmClient": "yarn",
  "webDir": "www",
  "plugins": {
    "FirebaseAuthentication": {
      "skipNativeAuth": false,
      "providers": [
        "google.com"
      ]
    }
  }
}
```

**Capacitor doctor:**
```
Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/ios: 3.3.2
```

**Comment by robingenz** [comment]
This message usually appears when the [installation instructions](https://github.com/robingenz/capacitor-firebase-authentication#installation) have not been followed correctly.
Please make sure you follow each step correctly.

If you have recently updated from Capacitor 2, make sure that the plugin is not registered in the `MainActivity.java`.

**Comment by jofftiquez** [comment]
Hi, @robingenz thanks for the reply. I will double-check everything. Yes, I am currently using Capacitor 3, I will check that as well. I'll give feedback the soonest.

**Comment by jofftiquez** [comment]
@robingenz after re-following the setup guide it's still not working. To give you a summary of what I have done. 

Context: I updated manually from cap 2 to cap 3, seems to be no issue as I can build successfully.

# 1. Properly installed required packages

![Screenshot_20211127_215740](https://user-images.githubusercontent.com/8638243/143684476-1fa945ec-e44b-426c-9681-32eedb6061d8.png)

# 2. Add firebase to android setup

**google-services.json**

> File present

![Screenshot_20211127_220509](https://user-images.githubusercontent.com/8638243/143684813-cb892654-eb4c-434e-b0f9-921ad7b74d37.png)

**root-level build.gradle**

```diff
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        jcenter()
+        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.1'
+        classpath 'com.google.gms:google-services:4.3.10'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        jcenter()
+        google()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**app-level app/gradle.build**

```diff
apply plugin: 'com.android.application'
+ apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "org.axie.account.tracker"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

repositories {
    flatDir{
        dirs '../capacitor-cordova-android-plugins/src/main/libs', 'libs'
    }
}

dependencies {
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoCoreVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidxJunitVersion"
+    implementation platform('com.google.firebase:firebase-bom:29.0.0')
+    implementation 'com.google.firebase:firebase-analytics'
+    implementation 'com.google.firebase:firebase-auth'
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(':capacitor-android')
    implementation project(':capacitor-cordova-android-plugins')
    testImplementation "junit:junit:$junitVersion"
}

apply from: 'capacitor.build.gradle'
apply plugin: 'com.google.gms.google-services'

```

# 3. App's SHA-1 setup done, and Auth Stragegy enabled already

# 4. Implementation

**src-capacitor/capacitor.config.json**

```json
{
  "appId": "org.axie.account.tracker",
  "appName": "Axie Dashboard",
  "bundledWebRuntime": false,
  "npmClient": "yarn",
  "webDir": "www",
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 0,
      "launchAutoHide": false,
      "backgroundColor": "#ffffff"
    },
    "PushNotifications": {
      "presentationOptions": [
        "badge",
        "sound",
        "alert"
      ]
    },
    "FirebaseAuthentication": {
      "skipNativeAuth": false,
      "providers": [
        "google.com"
      ]
    }
  }
}
```

**SignInPage.vue**

```javascript
// simply
const result = await FirebaseAuthentication.signInWithGoogle();
```

**Comment by jofftiquez** [comment]
> For future readers

Hi @robingenz you can close this now, It seems I have duplicated the importation of `apply plugin: 'com.google.gms.google-services'` in the **app-level gradle.build** as you can see above, it's in the top and in the bottom.

**Comment by jofftiquez** [comment]
Sorry for closing, I verified it's still not working.

**Comment by jofftiquez** [comment]
> For future readers

I think I figured it out. I forgot to import the `@robingenz/capacitor-firebase-authentication` in `src-capacitor/package.json`. Will close this now. Thank you.

**Comment by mburger81** [comment]
@jofftiquez Hey, I have exactly the same issue, what do you mean in "src-capacitor/package.json" 
What is this package.json? Do mean the normal package.json in the root? If yes the error you get should be a different

**Comment by jofftiquez** [comment]
> 

No, not the package.json in the root. I meant the package.json in `src-capacitory/package.json`.
