### ISSUE TITLE
signInWithGoogle result has no user property, only credentials

### ISSUE THREAD

**Issue by jofftiquez** [robingenz/capacitor-firebase-authentication#107]
**Plugin version:**
`^0.3.12`

**Platform(s):**
Android - Affected
Web - Okay

**Current behavior:**
When signing in using `FirebaseAuthentication.signInWithGoogle` the process proceeds as expected no issues whatsoever, but when you inspect the data being return here you will see that there's no `.user` property in the android version.

**Web**

![Screenshot_20211128_013110](https://user-images.githubusercontent.com/8638243/143691110-44ae76ac-7a59-4561-a5f0-640d6f989925.png)

**Android**

![Screenshot_20211128_013153](https://user-images.githubusercontent.com/8638243/143691123-74541a8c-7bff-4db1-968e-ceebc5bd7b66.png)

**Expected behavior:**
There should be a `.user` field in the result.

**Steps to reproduce:**
1. Implement in android.
2. Use `FirebaseAuthentication.signInWithGoogle` method.

**Related code:**
```
const result = await FirebaseAuthentication.signInWithGoogle();
console.warn('result', result);
```

**Capacitor doctor:**

```
Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/ios: 3.3.2
  @capacitor/android: 3.3.2
```

**Comment by robingenz** [comment]
Hi @jofftiquez,
thank you for the request.
Do you use the [`skipNativeAuth`](https://github.com/robingenz/capacitor-firebase-authentication#configuration) option?

**Comment by jofftiquez** [comment]
As a matter of fact, I set it to `true` for some reason. I'll change it to `false` and give feedback the soonest.

**Comment by jofftiquez** [comment]
That's it. It's working now. Thank you for this plugin @robingenz cheers!
