### ISSUE TITLE
bug: Error: invalid credential when signInWithCredential using idToken after closing & re-opening app

### ISSUE THREAD

**Issue by mpkasp** [robingenz/capacitor-firebase-authentication#109]
**Plugin version:** ^0.3.11

**Platform(s):** iOS

**Current behavior:**
I can successfully signInWithGoogle, get the idToken, then authenticate the js firebase sdk using the idToken calling signInWithCredential()
When I force-close the app and re-open it, the js SDK is no longer authenticated in Capacitor. This is a problem, I havent found a solution to.
To work around this I'm trying to grab the idToken from the plugin, and re-authenticate using the token since the SDK is now no longer returning authenticated.
I can successfully grab the idToken from the plugin, then when I try to **re**-authenticate the js firebase SDK using signInWithCredential, I get an error: .

**Expected behavior:**
Signing in with credential is successful between sessions.

**Steps to reproduce:**
1. Sign in with google, authenticate firebase js sdk using credentials:
```js
    const result = await FirebaseAuthentication.signInWithGoogle();
    const credential = GoogleAuthProvider.credential(result.credential?.idToken);
    return await signInWithCredential(this.auth, credential);
```
Ensure your init function initializes js listeners. Observe successfully authenticated the js sdk through the plugin.

When you initialize firebase, include the code below to signInWithCredential if an idToken exists.
```js
    const idToken = await FirebaseAuthentication.getIdToken();
    if (idToken?.token) {
      const credential = GoogleAuthProvider.credential(idToken.token);
      await signInWithCredential(this.auth, credential);
    }
```

2. Force close the app
3. Re-open the app
4. Observe the js sdk listener returns a null user, and when the init function's signInWithCredential is called, an error is returned:
"rejection":{"code":"auth/invalid-credential"...

**Capacitor doctor:**
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/core: 3.3.2
  @capacitor/android: 3.3.2
  @capacitor/ios: 3.3.2

Installed Dependencies:

  @capacitor/cli: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Hi @mpkasp,
thank you for the request and filling out the issue template.

Have you tried using the [`setPersistence`](https://firebase.google.com/docs/reference/js/auth.md#setpersistence) method?

Example:
```ts
import {
  browserLocalPersistence,
  getAuth,
  setPersistence,
} from 'firebase/auth';

setPersistence(getAuth(), browserLocalPersistence);
```

It should save the session and make sure you don't have to call `signInWithCredential` again.

**Comment by mpkasp** [comment]
@robingenz I actually did try this & it did not work, however it made me dive a bit more into the docs and got it to work by setting persistence when initializing auth in the js sdk from #78 specifically:

```js
    if (Capacitor.isNativePlatform()) {
      this.auth = initializeAuth(this.app, {persistence: browserLocalPersistence});
    } else {
      this.auth = getAuth();
    }
```

The key part that I did not have was `{persistence: browserLocalPersistence}`.

Still odd that it wouldn't let me re-authenticate using the idToken, but I'm happy with this solution and OK to close this.
