### ISSUE TITLE
Info about how to add firebase app

### ISSUE THREAD

**Issue by omar2205** [robingenz/capacitor-firebase-authentication#113]
**Plugin version:**
v0.4.0

**Platform(s):**
Android

**Current behavior:**
App crash on start. I'm trying to use the Firebase SDK. 

I want to know how to init Firebase. How to import the already initialized `app` and use it inside `signInWithGoogle`:

```js
// firebase.js
import { initializeApp } from 'firebase/app'
import { getAuth } from 'firebase/auth'

const firebaseConfig = { /* ... */ }
const app = initializeApp(firebaseConfig)
const auth = getAuth()
export { app, auth }

// ______

import { auth } from './firebase.js'

const signInWithGoogle = async () => {
  const result = await FirebaseAuthentication.signInWithGoogle()
  const credential = GoogleAuthProvider.credential(result.credential?.idToken)
  await signInWithCredential(auth, credential)
}
```

**Comment by robingenz** [comment]
Hi @omar2205,
thank you for your interest. 
Please make sure that you have followed the [installation instructions](https://github.com/robingenz/capacitor-firebase-authentication#installation) carefully.
[Here](https://github.com/robingenz/capacitor-firebase-authentication/blob/main/docs/setup-google.md) you can find the further installation steps for Google Sign-In.
If you want to use the Firebase JS SDK, please have a look at [this guide](https://github.com/robingenz/capacitor-firebase-authentication/blob/main/docs/firebase-js-sdk.md). 

This plugin uses the [`getAuth()`](https://firebase.google.com/docs/reference/js/auth.md#getauth) method of the Firebase JS SDK. You do not need to pass an object.

**Comment by omar2205** [comment]
Can you check this
https://github.com/omar2205/quick-cap-auth
?

**Comment by omar2205** [comment]
nvm, I found the problem, I redid everything multiple times, except adding this
```diff
ext {
+    rgcfaIncludeGoogle = true
}
```
