### ISSUE TITLE
bug: Facebook returns no email adress

### ISSUE THREAD

**Issue by ThcDelux3** [robingenz/capacitor-firebase-authentication#114]
Hey,

my facebook response does not contain an email. In Firebase (console) the email is registered. Any Idea why this issue occours?

I requested the advanced rights in the facebook developer center:

![image](https://user-images.githubusercontent.com/25651512/146998600-8da298d8-ffe5-4fa8-a45b-6508b96eafa3.png)

Also there is no error message. Do I have to activate something to "claim" the facebook email?

**Comment by robingenz** [comment]
Hi @ThcDelux3,
thank you for your request. 
I need some more information. Please fill in the bug template.
Also, I would like to know on which platform the problem occurs? Do you also not receive the email after the initial login?
I just tested it quickly and at least it worked for me. So I guess it should be a configuration problem.

**Comment by ThcDelux3** [comment]
**Plugin version:**

latest


**Platform(s):**

Android
not tested on iOS


**Current behavior:**

I get my reponse but there is no email in it


**Expected behavior:**

Return Email like google does


**Steps to reproduce:**

install plugin
setup firebase
add google login like in the docs
add facebook login like in the docs


**Related code:**

    async signInWithFacebook() {
      await FirebaseAuthentication.signInWithFacebook();

      const tokenResult = await FirebaseAuthentication.getIdToken();
      const userResult = await FirebaseAuthentication.getCurrentUser();

      console.log("USER:" + userResult);
      console.log("TOKEN:" + tokenResult);

    },
```
insert short code snippets here
```

**Other information:**




**Capacitor doctor:**


```
   Capacitor Doctor

Latest Dependencies:       

  @capacitor/cli: 3.3.3    
  @capacitor/core: 3.3.3   
  @capacitor/android: 3.3.3
  @capacitor/ios: 3.3.3    

Installed Dependencies:    

  @capacitor/core: 3.3.3   
  @capacitor/ios: 3.3.3    
  @capacitor/android: 3.3.3
  @capacitor/cli: 3.3.3    

[success] Android looking great! 👌
[error] Xcode is not installed
```

**Comment by ThcDelux3** [comment]
After click on the fb login button (  await FirebaseAuthentication.signInWithFacebook(); )

![image](https://user-images.githubusercontent.com/25651512/147001079-53447a2f-67b0-4a1d-a518-2661a964b5a2.png)

then i click continue

And I get these reults from facebook
![image](https://user-images.githubusercontent.com/25651512/147001248-74b53853-ce68-4d51-b0a9-546fae0be49b.png)

**Comment by robingenz** [comment]
I tested it again on my end and it works so far. Your configuration looks good too.
Please have a look at the following links:
- https://stackoverflow.com/a/55267301
- https://stackoverflow.com/a/37741550

Maybe this helps.

Have you tried it with another Facebook account? Does the same problem occur there?

**Comment by ThcDelux3** [comment]
Ok the problem was to allow the user to register with multiple provides for the same email. :) 👍🏻 
Thank you very much 💯 

 Any idea how to handle this scenario with this plugin or is this so far not possible?

**Comment by robingenz** [comment]
Great! Thank you for the update. In this case i will close this issue.

> Any idea how to handle this scenario with this plugin or is this so far not possible?

I found this in the [Firebase documentation](https://support.google.com/firebase/answer/9134820?hl=en):

> If you change the default setting by allowing multiple accounts to have the same email address, these functions will not retrieve profile information; if you need this information, you must retrieve it from the identity provider yourself.

So this does not seem to be possible with the Firebase SDK.
