### ISSUE TITLE
feat: Convert an anonymous account to a permanent account

### ISSUE THREAD

**Issue by davidecampello** [robingenz/capacitor-firebase-authentication#120]
Hi! Thank for this amazing plugin! Maybe there is a way to to this but I didn't found it. If so, please help me.

**Is your feature request related to a problem? Please describe:**
In my app users can sign in anonymously (now I'm using web sdk) or using  providers (email, google, ecc) using this plugin.
When they sign in anonymously they can link an account.
I can add an email/password account using web sdk but I would like also to add a google/ecc account using the plugin, but I can't do this.
Is it possible?

Here is the documentation of the web sdk
[https://firebase.google.com/docs/auth/web/anonymous-auth#convert-an-anonymous-account-to-a-permanent-account](url)

Many thanks!

**Comment by robingenz** [comment]
Hi @davidecampello,
thank you for your request!
Yes, you need this plugin for that. Unfortunately, this functionality does not exist yet. For this there is already a feature request, which includes these APIs: #27.
For this reason I would close this issue as a duplicate.
I plan to implement many features next month. Maybe I will manage this one as well.

Best regards!

**Comment by davidecampello** [comment]
Hi @robingenz! Thanks for your fast answer!
I didn't see the issue. I'll wait for the release. Thanks!
