### ISSUE TITLE
bug: Sign back in with Apple - Duplicate User

### ISSUE THREAD

**Issue by parambidja** [robingenz/capacitor-firebase-authentication#135]
**Plugin version:**
@robingenz/capacitor-firebase-authentication@latest

**Platform(s):**
iOS

**Current behavior:**
When I try to sign in with apple, the sign in process is prompted (Face ID, email setting, etc) and it works initially. Then I sign out and try to sign back in, and it fails to sign me in and does not let me continue.

I see an error log but I don't know why it's saying it's a duplicate user. I have an account so perhaps it's attempting to make another account instead of use the existing one?

Error message:
```
{
  "error": {
    "code": 400,
    "message": "MISSING_OR_INVALID_NONCE : Duplicate credential received. Please try again with a new credential.",
    "errors": [
      {
        "message": "MISSING_OR_INVALID_NONCE : Duplicate credential received. Please try again with a new credential.",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```

**Expected behavior:**
Sign in with apple succeeds for returning user.

**Steps to reproduce:**
1. Sign in with Apple
2. Sign out
3. Sign back in with Apple

**Related code:**
```
case 'apple':
            return async () => {
                // 1. Create credentials on the native layer
                const result = await FirebaseAuthentication.signInWithApple()
                // 2. Sign in on the web layer using the id token and nonce
                const provider = new OAuthProvider('apple.com')
                const credential = provider.credential({
                    idToken: result.credential?.idToken,
                    rawNonce: result.credential?.nonce,
                })
                const auth = getAuth()
                await signInWithCredential(auth, credential)
                return result
            }
```

**Capacitor doctor:**

```
❯ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

Installed Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

**Comment by robingenz** [comment]
Hi @parambidja,
thank you for your request.
How do you log out? Do you use the plugin method (https://github.com/robingenz/capacitor-firebase-authentication#signout)?

**Comment by robingenz** [comment]
Please sign out only once using the plugin's method. Does the error still occur then?

```diff
import { FirebaseAuthentication } from '@robingenz/capacitor-firebase-authentication'
...
-					getAuth().signOut().then(async () => {
                        await FirebaseAuthentication.signOut()
                        logEvent(EventName.PROFILE.SIGN_OUT)
-                    })
```

**Comment by robingenz** [comment]
No problem!
Do you allow multiple accounts with the same email address (see [here](https://support.google.com/firebase/answer/9134820?hl=en&ref_topic=6386702))?

**Comment by parambidja** [comment]
Perhaps useful information: it works fine through Safari but not on the mobile iOS app.

**Comment by robingenz** [comment]
> We do allow it right now.

Does the error also occur when you disable it?

**Comment by robingenz** [comment]
Okay, please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) so I can debug it.
