### ISSUE TITLE
bug: iOS directions fail to install required Firebase pods for M1 Mac

### ISSUE THREAD

**Issue by jwt02180** [robingenz/capacitor-firebase-authentication#141]
**Plugin version:**
0.4.3

**Platform(s):**
iOS

**Current behavior:**
I've followed the [example app](https://github.com/robingenz/capacitor-firebase-authentication-demo), and have google sign-in working on web.
Moving on to add the iOS platform, I followed the setup directions for iOS [here](https://github.com/robingenz/capacitor-firebase-authentication/blob/main/docs/setup-google.md#ios).
Running the command `npx cap update` produces the following message:

> ✖ update ios - failed!
> [error] Analyzing dependencies
>         [!] CocoaPods could not find compatible versions for pod "FirebaseCore":
>         In Podfile:
>         RobingenzCapacitorFirebaseAuthentication/Google (from
>         `../../node_modules/@robingenz/capacitor-firebase-authentication`) was resolved to 0.4.3, which depends on
>         Firebase/Auth (= 8.12.1) was resolved to 8.12.1, which depends on
>         Firebase/CoreOnly (= 8.12.1) was resolved to 8.12.1, which depends on
>         FirebaseCore (= 8.12.1)
>         
>         None of your spec sources contain a spec satisfying the dependency: `FirebaseCore (= 8.12.1)`.
>         
>         You have either:
>         * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
>         * mistyped the name or version.
>         * not added the source repo that hosts the Podspec to your Podfile.

Let me first say that I'm using an M1 MacBook Air, which tends to have an issue with CocoaPods sometimes.
I was able to resolve this error by running `arch -x86_64 pod install --repo-update` from the `ios/App` directory.
The Capacitor [docs](https://capacitorjs.com/docs/ios/troubleshooting#apple-silicon-ffi-bus-error) suggest I only need to run the `pod install` command specifying the architecture for the first time, but was how I knew that sometimes I'd need to do this command manually.

I'm not sure why the `--repo-update` flag was needed, so this might not be a bug for your plugin and is instead a developer environment thing.
Either way I wanted to document my experience in case anyone else runs into this, or if you determined that this is something that needed a fix.

**Expected behavior:**
Following the instructions should result in a successful installation for the iOS platform.

**Other information:**
Looking at old issues I found an [answer](https://github.com/robingenz/capacitor-firebase-authentication/issues/90) to my initial assumption of needing to add the Firebase/* pods myself (you don't, this plugin should handle that).

**Capacitor doctor:**
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.4.3
  @capacitor/ios: 3.4.3
  @capacitor/core: 3.4.3

[success] iOS looking great! 👌
```

**Comment by robingenz** [comment]
Hi @jwt02180,
thank you for this detailed request.

```
None of your spec sources contain a spec satisfying the dependency: `FirebaseCore (= 8.12.1)`.

You have either:
* out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
* mistyped the name or version.
* not added the source repo that hosts the Podspec to your Podfile.
````

I just updated the pods yesterday. So the pod versions are relatively new (released 27 days ago) and it is most likely that your source repo was out-of-date.
Are you sure that `arch -x86_64 pod install --repo-update`  was necessary? I also use an M1 MacBook and `pod install --repo-update` was sufficient for me.

The error message in the [Capacitor doc](https://capacitorjs.com/docs/ios/troubleshooting#apple-silicon-ffi-bus-error) also seems to be different than the one here.

> I'm not sure why the --repo-update flag was needed, so this might not be a bug for your plugin and is instead a developer environment thing.

Here is a good explanation: https://stackoverflow.com/a/45081972/6731412

> Either way I wanted to document my experience in case anyone else runs into this, or if you determined that this is something that needed a fix.

Thank you, I appreciate that and it certainly helps.

Please note that such specific things as how to deal with outdated pod spec references are out of scope of the documentation.
The documentation refers exclusively to the plugin and the necessary steps to set it up - not to the tools etc. that are needed for it. There are already very good documentations for this. If there are any questions, I would like to answer them in the GitHub issues/discussions.

For this reason, I am closing this issue. Please let me know if you have any other concerns.

Best regards
