### ISSUE TITLE
feat: support `onAuthStateChanged`

### ISSUE THREAD

**Issue by robingenz** [robingenz/capacitor-firebase-authentication#31]
**Is your feature request related to a problem? Please describe:**

Currently there is no option to be notified about a SignIn or SignOut.

**Describe the solution you'd like:**

Support [`onAuthStateChanged`](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onauthstatechanged).

`addListener('authStateChange', ...)`

**Comment by mesqueeb** [comment]
@robingenz isn't this possible just with the Firebase JS SDK? Or does this plugin not authenticate the web layer?

**Comment by robingenz** [comment]
@mesqueeb see https://github.com/robingenz/capacitor-firebase-authentication/issues/41#issuecomment-883559964
