### ISSUE TITLE
Question: Support for Capacitor v2.x?

### ISSUE THREAD

**Issue by mesqueeb** [robingenz/capacitor-firebase-authentication#42]
Does this library support Capacitor v2.x?

**Comment by mesqueeb** [comment]
I'd recommend adding a short overview in the readme on which Capacitor versions are supported, and which Firebase JS SDK versions are supported.

For Firebase, I'm at v8, but I still see a lot of v7, v8 and some already use the yet unreleased v9.

**Comment by robingenz** [comment]
Hi, thank you for this question.
This library supports only Capacitor 3.
This plugin is intended to be used on Android and iOS without the Firebase JS SDK.
However, as I wrote in https://github.com/robingenz/capacitor-firebase-authentication/issues/41#issuecomment-883559964, you should be able to use the Firebase JS SDK without any problems.
I will always try to keep the plugin compatible to the latest stable Firebase JS SDK.
