### ISSUE TITLE
feat: Phone verification

### ISSUE THREAD

**Issue by mishrasatyam** [robingenz/capacitor-firebase-authentication#57]
Thank you for creating this package!!

**Is your feature request related to a problem? Please describe:**
I hope you would  add firebase's phone verification added.

**Comment by robingenz** [comment]
Thank you for your feature request!
This is definitely a must-have.

**Comment by robingenz** [comment]
This plugin now supports authentication using a Phone Number. 
You can give it a try:
```
npm i @robingenz/capacitor-firebase-authentication@0.3.6
```
