### ISSUE TITLE
bug: FirebaseAuth not found after installing other Capacitor Plugin

### ISSUE THREAD

**Issue by ThcDelux3** [robingenz/capacitor-firebase-authentication#75]
**Plugin version:**

Latest

**Platform(s):**

Android

**Current behavior:**

Login not working after adding this plugin https://github.com/capacitor-community/camera-preview

**Expected behavior:**

Login should work as it did before installing https://github.com/capacitor-community/camera-preview

**Steps to reproduce:**

Setup new project
install capacitor-firebase-authentication
add android implementation
add web implementtation
check if the login works
npm / yarn install capacitor-firebase-authentication
add this code to mainactivity.java

public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
            // Additional plugins you've installed go here
            // Ex: add(TotallyAwesomePlugin.class);
            add(CameraPreview.class);
        }});
    }
}

After a successful gradel build the login isn't working anymore. Web still works no testing on iOS so far.

Error message in Android Studio:
E/Capacitor/Console: File: http://localhost/js/chunk-vendors.08187ed4.js - Line 26 - Msg: Error: "FirebaseAuthentication" plugin is not implemented on android

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/ios: 3.2.0

Installed Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/ios: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/core: 3.2.0

[success] Android looking great! �
[error] Xcode is not installed

**Comment by merganon** [comment]
capacitor-community/camera-preview is not supported for Capacitor 3
See https://github.com/capacitor-community/camera-preview/pull/146

**Comment by merganon** [comment]
>     this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
>        // Additional plugins you've installed go here
>       // Ex: add(TotallyAwesomePlugin.class);
>      add(CameraPreview.class);

If you see any plugin that tells you to import the plugin like that, it's not supported for Capacitor 3
Starting with Capacitor 3 it will automatically import the plugin and you don't need to touch the MainActivity.java file

**Comment by ThcDelux3** [comment]
Ahhh Ok thanks :) Didn't know about that.
