### ISSUE TITLE
bug: Missing Nonce - Sign In with Apple on iOS with Javascript SDK

### ISSUE THREAD

**Issue by roldyclark** [robingenz/capacitor-firebase-authentication#87]
It seems that the nonce returned by `FirebaseAuthentication.signInWithApple()` is invalid, or `provider.credential` is not building the credential correctly. 

Code:
```
export async function appleLogin() {
  // 1. Create credentials on the native layer
  const result = await FirebaseAuthentication.signInWithApple()
  // 2. Sign in on the web layer using the id token and nonce
  const provider = new OAuthProvider('apple.com')
  const credential = provider.credential({
    idToken: result.credential?.idToken,
    rawNonce: result.credential?.nonce
  })
  await signInWithCredential(auth, credential)
}
```
Error:
`Unhandled Promise Rejection: FirebaseError: Firebase: Nonce is missing in the request. (auth/missing-or-invalid-nonce).`

**Comment by roldyclark** [comment]
Put in this issue with Firebase as well: https://github.com/firebase/firebase-js-sdk/issues/5553#issuecomment-928193787

**Comment by robingenz** [comment]
Thank you for your request. Are the two properties `result.credential?.idToken` and `result.credential?.nonce` defined or undefined?

**Comment by mdepasquale21** [comment]
having the exact same error, but `idToken` and `nonce` are defined (at least in my case)

**Comment by roldyclark** [comment]
@robingenz both are defined :/ I think it's an issue with the provider.credential method

**Comment by roldyclark** [comment]
code:  
```
const credential = new OAuthProvider('apple.com').credential({
    idToken: result.credential?.idToken,
    rawNonce: result.credential?.nonce
  })
  console.log('credenital:' + JSON.stringify(credential))
```
result:
`credenital:{"idToken":"XXXX","pendingToken":null,"providerId":"apple.com","signInMethod":"apple.com"}`

as you can see, it build a credential without the nonce

**Comment by roldyclark** [comment]
and credential.rawNonce warns: Property 'rawNonce' does not exist on type 'OAuthCredential'.

**Comment by roldyclark** [comment]
@mdepasquale21 @robingenz Found a workaround for now:
```
  const credential = OAuthProvider.credentialFromJSON({
    providerId: 'apple.com',
    signInMethod: 'apple.com',
    idToken: result.credential?.idToken,
    nonce: result.credential?.nonce,
    pendingToken: null
  })
```

**Comment by robingenz** [comment]
Great! Thanks for your investigation @roldyclark.
In this case, `nonce` appears to be neither missing nor invalid.
For this reason, I am closing this issue.

**Comment by mesqueeb** [comment]
@roldyclark 
this release note seems sus....
<img width="710" alt="image" src="https://user-images.githubusercontent.com/3253920/136500143-00793ceb-a199-46eb-9d23-e25b1eac4b72.png">

I'll check it and report my findings : D
