### ISSUE TITLE
feat: Firebase 8.1 compatible version

### ISSUE THREAD

**Issue by mesqueeb** [robingenz/capacitor-firebase-authentication#88]
**Is your feature request related to a problem? Please describe:**

Is there a Firebase 8.1 compatible version you can provide? Or is it too much work?

**Describe alternatives you've considered:**

**Comment by robingenz** [comment]
Hi @mesqueeb,
unfortunately I can only support one Firebase version in my main branch. I would need to create a second branch with a new web implementation. However, keeping these two branches in sync would be too much effort in the long run.
For this reason, I am closing this Issue.

Have you already tried to update to [Firebase v9 compat](https://firebase.google.com/docs/web/modular-upgrade#update_imports_to_v9_compat)? Should be little effort and you do not need major code changes.

**Comment by mesqueeb** [comment]
@robingenz I was able to upgrade the other dependencies to use v9 compat for now! Now I will continue to upgrade the main app to v9 compat and see how it goes.

Thank you very much for your continued support.

BTW, does your library already use modular Firebase v9 code? Or does it also still rely on the compat build?

Best regards

**Comment by robingenz** [comment]
Great! 
This plugin already uses the Firebase v9 modular style.
