### ISSUE TITLE
suggestion: convert single class to standalone functions

### ISSUE THREAD

**Issue by mesqueeb** [robingenz/capacitor-firebase-authentication#89]
Hey @robingenz 
I was reading your source code and I see that you're using a single class with methods for the web code:

https://github.com/robingenz/capacitor-firebase-authentication/blob/ae3ed78502935238b6f8c27b3b02b6c8cc8446bd/src/web.ts#L27

However, the issue with a big class with methods is that when we don't use some of the providers on there, all those functions are still bundled with our code via webpack/rollup. Because a class can't be tree-shooken I think?

Will you consider rewriting these as just stand-alone functions and exporting each function separately instead?

**Comment by robingenz** [comment]
Hi @mesqueeb,
this should not be a problem in the web implementation.
Unlike the native implementation, which sometimes requires third-party SDKs, the web implementation uses only the popup-based OAuth authentication flow.
The only differences are the different OAuthProvider classes. However, these are very small and negligible.

> Because a class can't be tree-shooken I think?

Unfortunately I don't know if class methods are tree shakeable.

> Will you consider rewriting these as just stand-alone functions and exporting each function separately instead?

Unfortunately, I don't know if calling these stand-alone functions could still address the native implementation.
Suggested solutions are welcome.
For now, I will not consider this.
