### ISSUE TITLE
question: How can we use FirebaseAuthentication without passing firebaseApp or auth instances?

### ISSUE THREAD

**Issue by mesqueeb** [robingenz/capacitor-firebase-authentication#91]
What I don't understand about this library is this part:
```js
import { FirebaseAuthentication } from '@robingenz/capacitor-firebase-authentication';
```

This makes it possible to use all the auth functions, but we never need to pass our initialised `firebaseApp` or `auth` objects?

**Comment by robingenz** [comment]
Great question!
This plugin uses the [`getAuth()`](https://firebase.google.com/docs/reference/js/auth#getauth) method from the Firebase JS SDK v9. It returns the Auth instance associated with the provided FirebaseApp. See this [example](https://github.com/robingenz/capacitor-firebase-authentication/blob/ae3ed78502935238b6f8c27b3b02b6c8cc8446bd/src/web.ts#L61).
The initialization is not done by the plugin. The developer is responsible for initializing the FirebaseApp before using the plugin. The plugin then uses the active FirebaseApp instance.
Let me know if you have more questions.
