### ISSUE TITLE
request: Add twitter auth example (ios with skipNativeAuth)

### ISSUE THREAD

**Issue by mesqueeb** [robingenz/capacitor-firebase-authentication#93]
Based on these docs:

https://github.com/robingenz/capacitor-firebase-authentication/blob/main/docs/firebase-js-sdk.md

I tried to implement Twitter:

```ts
  async function signinWithTwitter(): Promise<void> {
    // 1. Create credentials on the native layer
    const result: SignInResult = await FirebaseAuthentication.signInWithTwitter()
    if (!result.credential?.idToken || !result.credential?.secret) {
      throw new Error('Twitter error')
    }
    // 2. Create credentials on the web layer
    const credential = TwitterAuthProvider.credential(
      result.credential?.idToken,
      result.credential?.secret
    )
    // 3. Sign in on the web layer using the id token
    await signInWithCredential(firebaseAuth, credential)
  }
```

However, that doesn't work. The `result` looks like:

<img width="420" alt="image" src="https://user-images.githubusercontent.com/3253920/136235656-2e8b5fa2-1c61-4001-a470-e9dd3e22c4e6.png">

I don't get the `idToken` and `secret`.

It seems like Twitter works with redirect detection....?
I do see the redirection URL: do we need to parse something from here?

<img width="1366" alt="Screenshot 2021-10-07 at 0 23 20" src="https://user-images.githubusercontent.com/3253920/136234660-6ff829dd-b78d-47d9-b577-f1f700278b8f.png">

All help much appreciated!

my config:
```
"FirebaseAuthentication": {
      "skipNativeAuth": true,
      "providers": [
        "apple.com",
        "google.com",
        "twitter.com"
      ]
    },
```

**Comment by robingenz** [comment]
Oh, I will have to take a closer look at this. I'll try to find some time this weekend. Thank you for this report.
Does it work on Android?

**Comment by mesqueeb** [comment]
@robingenz let me know if there's anything I can help you with this weekend.
