### ISSUE TITLE
feat: Find a way to prevent Facebook SDK to be included into app source code

### ISSUE THREAD

**Issue by mesqueeb** [robingenz/capacitor-firebase-authentication#96]
**Is your feature request related to a problem? Please describe:**
<-- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] -

We don't use Facebook authentication in our app. But I believe the FBSDK is still included in the built app.

**Describe the solution you'd like:**
<-- A clear and concise description of what you want to happen. -→

I'd love to find a way to prevent any FBSDK code from being included in my app.

**Describe alternatives you've considered:**
<-- A clear and concise description of any alternative solutions or features you've considered. -

Fork this repo.

**Additional context:**
<-- Add any other context or screenshots about the feature request here. -

Much much lower priority than #93 !!

**Comment by robingenz** [comment]
Thank you for your request. This is definitely a topic I would like to tackle in the long term.
If anyone has ideas on how to best solve this, I would greatly appreciate any tips.

**Comment by robingenz** [comment]
It took a day but I finally found a solution. 🎉 
I will release an update today.
