### ISSUE TITLE
bug: Error: 10

### ISSUE THREAD

**Issue by yaron1m** [robingenz/capacitor-firebase-authentication#97]
**Plugin version:** 0.3.11

**Platform(s):** Android

**Current behavior:** When signing in with Google, after choosing the right Google account I get the following error:
```
Error: 10: 
    at Object.cap.fromNative ((index):426)
    at <anonymous>:1:18
```

**Expected behavior:** Sign in successfully.

**Steps to reproduce:**
1. Install plugin.
2. Call `FirebaseAuthentication.signInWithGoogle()`
3. Choose account

This happens both when `skipNativeAuth` is true and false, running on Android Simulator

**Capacitor doctor:**

```
Latest Dependencies:

  @capacitor/cli: 3.3.0
  @capacitor/core: 3.3.0
  @capacitor/android: 3.3.0
  @capacitor/ios: 3.3.0

Installed Dependencies:

  @capacitor/cli: 3.2.4
  @capacitor/android: 3.2.4
  @capacitor/core: 3.2.2
  @capacitor/ios: 3.2.4

```

**Comment by robingenz** [comment]
Hi @yaron1m,
thank you for your request.

I have never tested the plugin in the Android emulator. I will give this a try this weekend.

The error looks like error code 10 ([DEVELOPER_ERROR](https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes.html#DEVELOPER_ERROR)) from Google Play Services.
Please have a look at this [comment](https://github.com/googlesamples/google-services/issues/360#issuecomment-381648685).
Make sure your app is configured correctly in the Google API Console/Firebase Console (specifically the SHA1).

Let me know if this helps you.
I will get back to you as soon as I have tested the plugin in the emulator.

**Comment by robingenz** [comment]
Quick update: I tested it on an Android emulator. It worked without any problems.

**Comment by yaron1m** [comment]
The issue was indeed with the SHA1.

After updating it in Firebase issue was resolved.

Thanks!
